component reviewAndRating completed
David-j787/E-Commerce-G7 pull request #62
Opened 2022-03-23 15:32 UTC by Fyzz02

Crear un componente por separado donde se pueda dejar una review y un sistema de 5 estrellas (rating)

2022-03-23 15:42 UTC, bserra7 approved these changes

2022-03-23 17:50 UTC, donxepe commented
el dispatch de la accioon para hacer el post del review al backend sería parte de otra tarea?

2022-03-23 21:40 UTC, bserra7 requested changes
deberia hacerse en éste componente, falta la funcionalidad de guardar el comentario en bases de datos

2022-03-24 18:54 UTC, bserra7 approved these changes

2022-03-24 18:54 UTC, merged